spring:
  application:
    name: kafka
#spring.kafka.consumer.group-id=myGroup-kafka
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.bootstrap-servers=18.219.169.184:9092
#spring.kafka.consumer.properties.spring.json.trusted.packages=com.dac.kafka.model

#spring.kafka.producer.bootstrap-servers=18.219.169.184:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

  server:
    port: 8080
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_I2ljKXMXt
aws:
  region: us-east-2
  sns:
    topic:
      arn-mail: arn:aws:sns:us-east-2:205709488040:SNS-Notification-test
      arn-sms: arn:aws:sns:us-east-2:205709488040:SNS-Notification-test
